#ifndef FLUIDS_H
#define FLUIDS_H
enum {
	  ANIMATE_ID, 
	  SCALAR_COLORING_ID, 
	  DRAW_HEDGEHOGS_ID, 
	  DRAW_MATTER_ID, 
	  DIRECTION_COLOR_ID, 
	  NEXT_COLOR_ID, 
	  TIMESTEP_SPINNER_ID, 
	  HEDGEHOG_SPINNER_ID, 
	  VISCOSITY_SPINNER_ID, 
	  NUM_COLOR_SPINNER_ID, 
	  LIMIT_COLORS_ID,
	  SATURATION_SPINNER_ID, 
	  HUE_SPINNER_ID
};

#endif