#ifndef FLUIDS_H
#define FLUIDS_H
GLUI_Spinner* minClamp, *maxClamp;
enum {
	  ANIMATE_ID, 
	  DRAW_HEDGEHOGS_ID, 
	  DRAW_MATTER_ID, 
	  DIRECTION_COLOR_ID, 
	  NEXT_COLOR_ID, 
	  TIMESTEP_SPINNER_ID, 
	  HEDGEHOG_SPINNER_ID, 
	  VISCOSITY_SPINNER_ID, 
	  NUM_COLOR_SPINNER_ID, 
	  LIMIT_COLORS_ID,
	  SATURATION_SPINNER_ID, 
	  HUE_SPINNER_ID,
	  SCALE_CLAMP_ID,
	  COLOR_MAP_ID,
	  DATASET_ID,
	  GLYPH_LOCATION_ID,
	  X_GLYPH_SPINNER,
	  Y_GLYPH_SPINNER,
	  GLYPH_SHAPE_ID,
	  MIN_CLAMP_ID,
	  MAX_CLAMP_ID
};

#endif