C++        = g++
OBJECTS1    = fluids.o
OBJECTS2	= 
CFILES      = $(OBJECTS:.o=.c)
EXECFILE    = smoke
LIBS        = -lglut -lrfftw -lfftw -lGL -lGLU -lm
#Possible flags for release (ffast-math uses less precision for floating-point numbers, check that your application can handle this)
#CFLAGS      = -O3 -march=x86-64 -mtune=generic -DNDEBUG -mfpmath=sse -ffast-math -Wall -pipe
#Debug flags
CFLAGS      = -ggdb -Wall -pipe
LINKFLAGS   =


.SILENT:

all: $(EXECFILE)

$(EXECFILE): $(OBJECTS)
		$(C++) $(LINKFLAGS) $(OBJECTS) -o $(EXECFILE) $(LIBDIRS) $(LIBS)

.c.o: $$@.c $$@.h
		cc $(CFLAGS) $(INCLUDEDIRS) -c $<

clean:
		-rm -rf $(OBJECTS) $(EXECFILE)

depend:
		gcc -MM $(CFILES) > make.dep

-include make.dep